### ISSUE TITLE
Maybe a typo?

### ISSUE THREAD

**Issue by thekaveman** [CityofSantaMonica/analytics.smgov.net#15]
Or maybe I'm missing something: [`aggregate_list_sum` in aggregate/run.py](https://github.com/CityofSantaMonica/analytics.smgov.net/blob/master/App_Data/jobs/triggered/aggregate/run.py#L78-L80)

``` python
if key not in output:
   output[key] = item
   output[key][sumKey] = int(output[key][sumKey]) #here
else:
   output[key][sumKey] += int(item[sumKey])
```

don't we want to initialize `output[key][sumKey]` with `int(item[sumKey])`?

@allejo

**Comment by allejo** [comment]
Yea probably a typo or lack of consistency on my part; I have no preference for one or the other since `output[key][sumKey]` & `item[sumKey]` are identical.

**Comment by thekaveman** [comment]
But at that point, are they? 

Since `key` does not yet exist in `output` (and hence `sumKey` doesn't yet exist in `output[key]`), I think the result of `int(output[key][sumKey])` is always **0** on that line, right?

**Comment by thekaveman** [comment]
Ahhh yes, I see now. No typo. The difference between the two lines just stuck out for some reason :smile:
