### ISSUE TITLE
Move site into production

### ISSUE THREAD

**Issue by thekaveman** [CityofSantaMonica/analytics.smgov.net#18]
This supersedes #4 

We've finally gotten our Azure ducks in a row. Let's deploy this thing!

**Comment by thekaveman** [comment]
@allejo let's talk when you're in - there are a few things to do on the Azure side

**Comment by allejo** [comment]
And, we're live and fully (except Socrata) working! http://analytics.smgov.net/

Edit: Socrata's working!
