### ISSUE TITLE
Poll and aggregate multiple "agencies"

### ISSUE THREAD

**Issue by thekaveman** [CityofSantaMonica/analytics.smgov.net#2]
Unlike the [DAP](http://www.digitalgov.gov/services/dap/), we don't have _One Analytics Account to Rule Them All_

Sites such as http://bigbluebus.com, http://smpl.org, and http://santamonicapd.org are tracked under different accounts, different properties, different views :cry: 

It would be really cool if we could poll all of our individual "agencies" - BBB, library, police, fire, others - and aggregate into unified data files (one for each report type), to be consumed by the dashboard.

**Comment by allejo** [comment]
@thekaveman would you be able to add `.env` files with the other IDs? I can tackle aggregating the data from there

**Comment by thekaveman** [comment]
@allejo will do

**Comment by thekaveman** [comment]
see 361d487

**Comment by allejo** [comment]
Progress of [`aggregation`](https://github.com/CityofSantaMonica/analytics.smgov.net/tree/aggregation) branch:
- [x] Aggregate the data
  - [x] Figure out how to keep same structure of each data object ([it's hard coded atm](https://github.com/CityofSantaMonica/analytics.smgov.net/blob/aggregation/App_Data/jobs/triggered/aggregate/run.py#L40-L42))
- [ ] Check to see if the data looks correct
- [x] Aggregate CSV data too?
- [ ] Get this working on Azure with the correct paths
- [ ] Clean up

**Comment by thekaveman** [comment]
Would it be possible to just turn the aggregated JSON into CSV? (Rather than re-aggregating into CSV)

**Comment by allejo** [comment]
Yea it would be, the CSV files are typically the `data` array in the JSON data or some other unique values like `totals['totals']['browser']` (e.g. browser.json)

**Comment by allejo** [comment]
Moved to #9
