### ISSUE TITLE
HTTPS?

### ISSUE THREAD

**Issue by konklone** [CityofSantaMonica/analytics.smgov.net#20]
Congrats on the launch! Any chance of moving the site to [HTTPS-only](https://https.cio.gov/everything/)? It'd be a great way to lead by example for the rest of the city.

**Comment by thekaveman** [comment]
Thanks for the suggestion! @smcor3dump and I have been discussing how to bring HTTPS to more of the City's sites. This dashboard would certainly be an easy win in that regard (ideally, all of the sites _presented on the dashboard_ would also be HTTPS only!); we'll get back when we have a better plan.

**Comment by konklone** [comment]
One thing I've been harassing @tdlowden to do on the federal side is to [track the protocol of the site being logged](https://github.com/digital-analytics-program/gov-wide-code/issues/35) in the analytics collection code. That way this information could be surfaced at least in the dashboard's downloadable data, if not the dashboard itself.

That would be a great way to start finding where your highest ROI would be on converting City sites to HTTPS. And ample incentive to get the dashboard HTTPS itself. :)
