### ISSUE TITLE
Empty lines in download CSV

### ISSUE THREAD

**Issue by konklone** [CityofSantaMonica/analytics.smgov.net#22]
There are empty lines in each of the download CSVs I tried:

![image](https://cloud.githubusercontent.com/assets/4592/15564628/30ef54ee-22e2-11e6-9c0f-d2403cac618b.png)

I am not sure what the underlying issue might be, but I double-checked analytics.usa.gov and didn't see that issue there.

**Comment by thekaveman** [comment]
That commit looks good - I'm not seeing any blank lines

**Comment by allejo** [comment]
Good catch! We're using our own Python script to aggregate data (also generates our CSV files) for all of our websites and that was the cause of the blank lines; it wasn't related to analytics-reporter 👍 

Python on Windows writes line endings as `\r\n` but treating the CSV file as a binary file (`wb+`) corrects the blank lines.

**Comment by konklone** [comment]
:+1: Glad to help!
