### ISSUE TITLE
Batch the Socrata calls

### ISSUE THREAD

**Issue by thekaveman** [CityofSantaMonica/analytics.smgov.net#34]
We're getting timeouts when pushing to Socrata. Likely because we're trying to send 2K+ records at once.

Let's batch the calls (start with size 1000) and see if that makes a difference.

**Comment by allejo** [comment]
See 76eafe762b9a792c5b1efe9d6657435272834975. It worked with 950 calls... 1000 still kept timing out

**Comment by thekaveman** [comment]
¯_(ツ)_/¯
