### ISSUE TITLE
all-pages.json limitations

### ISSUE THREAD

**Issue by allejo** [CityofSantaMonica/analytics.smgov.net#36]
> ERROR AFTER QUERYING: Error: Requested 12 metrics; only 10 are allowed.

This file is having issues: [`_reports/all-pages.md`](https://github.com/CityofSantaMonica/analytics.smgov.net/blob/master/_reports/all-pages.md)

**Comment by thekaveman** [comment]
Hmmm guess we need to lose a few metrics. I'll take a look.
