### ISSUE TITLE
Configure the Azure site with custom domain

### ISSUE THREAD

**Issue by thekaveman** [CityofSantaMonica/analytics.smgov.net#4]
This is just a reminder, as we get closer to being ready to go live, you know, _officially_.

**Comment by allejo** [comment]
With regards to the comment, https://github.com/CityofSantaMonica/analytics.smgov.net/commit/71fbe3498d7e618de1c18f434c5f38384ef699b3 does give us [the "domain" value](http://csmanalytics.azurewebsites.net/data/smgov/top-pages-realtime.json) that we need, I just think the JS isn't [doing anything with it](https://github.com/CityofSantaMonica/analytics.smgov.net/blob/master/js/index.js#L306).

**Comment by thekaveman** [comment]
Indeed, solid find in the JS!
