### ISSUE TITLE
Remove BBB Store from sites

### ISSUE THREAD

**Issue by thekaveman** [CityofSantaMonica/analytics.smgov.net#48]
This site isn't currently active, no reason to take up GA quota.

**Comment by allejo** [comment]
Removed in 55aa4242a30c398461bf9611ed7acd62554453c4 on the [`feature/domain-selector-47`](https://github.com/CityofSantaMonica/analytics.smgov.net/tree/feature/domain-selector-47) branch

**Comment by allejo** [comment]
Extracted from the [`feature/domain-selector-47`](https://github.com/CityofSantaMonica/analytics.smgov.net/tree/feature/domain-selector-47) branch and removed in #52
