### ISSUE TITLE
Add santamonica.gov to tracked websites

### ISSUE THREAD

**Issue by thekaveman** [CityofSantaMonica/analytics.smgov.net#56]

**Comment by thekaveman** [comment]
@allejo when you have some time, can you take a look at this? For some reason the [Travis build is failing](https://travis-ci.org/CityofSantaMonica/analytics.smgov.net), but I can't see why. I'm pretty sure everything is setup in Google analytics correctly, but since the site won't build, it won't deploy this latest website environment file.

**Comment by allejo** [comment]
I wonder if this has to do with Travis killing the script because of memory consumption. Early on I ran into issues with getting Python dependencies installed on Azure correctly but would you be open to testing getting Python dependencies (only sodapy and its deps) installed on Azure again. If support has improved on Azure, then we can nuke the virtualenv workaround (one less thing for Travis to do).

**Comment by thekaveman** [comment]
I'd be totally fine with trying the Azure approach again - I just won't be able to work on it for the next couple of weeks as I am going out of town and likely won't be connected to the interwebs

**Comment by allejo** [comment]
That's no problem, I'll test it in a separate Azure instance and go from there.

**Comment by allejo** [comment]
I did my best to replicate everything on my own repos, Travis account, and Azure apps but needs to be tested on here as well.

Ok! So finally made some progress on figuring out this problem. The current `master` branch has moved away from using Travis to build a virtual Python environment and Kudu is now taking care of the deps installation. The Python 3.6.1 Azure extension has been installed on our app service and that's what is being used to fetch dependencies (sodapy and its deps).

https://travis-ci.org/CityofSantaMonica/analytics.smgov.net/builds/285459835#L783-L786

The issue in that link above is related to our app's git storage. *I think?* The way I got this sorted out on my own Azure app was doing a manual push to the git URL available in the Azure Portal (`Properties > GIT URL`) and then the subsequent Travis builds seem to work fine. So what you'd have to do is do a quick commit and force push or replicate what Travis currently does:

1. Build the site
2. Remove `fake-data/`
3. Force add `_site` with `git add -f _site`
4. Add a new remote to Azure's git URL and push with `-f` or `--force`

Mind taking a looking around Azure's logs/setup for any more info? The only other thing I can think of doing if the above doesn't work would be to remove the git storage and add it again. Anyhow, the issue has moved away from Travis and onto Azure now 👍

**Comment by thekaveman** [comment]
Thanks for the work on this and the tips @allejo - I've got the Travis builds working and deploying again. 

We now have a different issue that will be related to #57, discovered while I was making a quick commit to force a rebuild/redeploy from Travis. I'll keep investigating and use #57 to document any needed changes.
