### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by allejo** [CityofSantaMonica/analytics.smgov.net#6]
Check all the links to generated JSON files and ensure they aren't broken. The "download datasets" option at the very bottom have a few broken links

**Comment by thekaveman** [comment]
Same with "Download the full dataset" link at the top of the page.

This could be due to a missing `mime-type` for `text/csv`? Notice [realtime JSON](http://csmanalytics.azurewebsites.net/data/smgov/realtime.json) serves just fine.

**Comment by allejo** [comment]
Fixed in acc84dd5e44caa1e421c71597e01f9c905f90199. Broken links won't be deployed anymore, see: 3fa2b925b9362af3b241c8421da4b6cfda588c4a
